openapi: 3.1.1
info:
  title: Api rest demo
  description: A demo project for setting up an api rest with Spring Boot.
  version: 1.0.0-SNAPSHOT
  contact:
    name: Contact the developer
    url: 'https://github.com/ilizin'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'http://swagger.io/terms/'

externalDocs:
  description: Find out more about Swagger
  url: 'https://swagger.io/'

paths:
  /v1/sqrt/{value}:
    get:
      summary: Calculate the square roots of a positive number
      description: Calculate the square roots of a positive number using the Heron algorithm
      tags:
        - Number controller
      parameters:
        - in: path
          name: value
          required: true
          description: A positive number the square root must be calculated
          example: 4
          schema:
            type: integer
      responses:
        "200": # status code
          description: Successfully calculation
          content:
            application/json:
              schema:
                type: integer
              example:
                4
        "400": # status code
          description: Incorrect input value
          content:
            application/json:
              schema:
                type: array

  /v1/prime/{value}:
    get:
      summary: Check if a number is a prime number
      description: Return true if the number is prime else return false
      tags:
        - Number controller
      parameters:
        - in: path
          name: value
          required: true
          description: An integer number you want to check if it's prime
          example: 11
          schema:
            type: integer

      responses:
        "200": # status code
          description: Successfully calculation
          content:
            application/json:
              schema:
                type: array

  /v1/palindrome/{value}:
    get:
      summary: Check if a string is palindrome or not
      description: Return true if the string is palindrome, else false
      tags:
        - String controller
      parameters:
        - in: path
          name: value
          required: true
          description: A word to be checked if it's palindrome or not
          example: Level
          schema:
            type: string
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: boolean
              example:
                true
        "400": # status code
          description: Incorrect input value
          content:
            application/json:
              schema:
                type: array